import "./Partnership.css";

const Partnership = () => {
  return (
    <section className="partnership">
      <h2>A strong partnership</h2>
      <p>
        Over the years we built a strong relationship with a network of leading
        brands.
      </p>
      <div className="scroll-container">
        <p id="first_paragraph">
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
          HUBLOT OMEGA HAMILTON LONGINES RADO TISSOT BAUME ET MERCIER BREITLING
        </p>

        <p id="second_paragraph">
          OROTREND JEWELS GIOVANNI FERRARIS JEWELS INDYGO JEWELS OROTREND JEWELS
          GIOVANNI FERRARIS JEWELS INDYGO JEWELS OROTREND JEWELS GIOVANNI
          FERRARIS JEWELS INDYGO JEWELS OROTREND JEWELS GIOVANNI FERRARIS JEWELS
          INDYGO JEWELS OROTREND JEWELS GIOVANNI FERRARIS JEWELS INDYGO JEWELS
          OROTREND JEWELS GIOVANNI FERRARIS JEWELS INDYGO JEWELS OROTREND JEWELS
          GIOVANNI FERRARIS JEWELS INDYGO JEWELS OROTREND JEWELS GIOVANNI
          FERRARIS JEWELS INDYGO JEWELS OROTREND JEWELS GIOVANNI FERRARIS JEWELS
          INDYGO JEWELS OROTREND JEWELS GIOVANNI FERRARIS JEWELS INDYGO JEWELS
          OROTREND JEWELS GIOVANNI FERRARIS JEWELS INDYGO JEWELS OROTREND JEWELS
          GIOVANNI FERRARIS JEWELS INDYGO JEWELS OROTREND JEWELS GIOVANNI
          FERRARIS JEWELS INDYGO JEWELS OROTREND JEWELS GIOVANNI FERRARIS JEWELS
          INDYGO JEWELS OROTREND JEWELS GIOVANNI FERRARIS JEWELS INDYGO JEWELS
        </p>

        <p id="third_paragraph">
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
          GAVELLO CERVERA BARCELONA NANIS GAVELLO CERVERA BARCELONA NANIS
        </p>
        <p id="fourth_paragraph">
          PINETTI LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN PINETTI
          LOCHERBER MAX BENJAMIN PINETTI LOCHERBER MAX BENJAMIN
        </p>
      </div>
    </section>
  );
};

export default Partnership;
